# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
# используем режим обычного пользователя для сборки проекта.
sudo: false

# запуск базы PostrgresSQL
services:
  - postgresql

# создание базы данных с именем пользователя postgres и пустым паролем
  before_script:
    - psql -c 'create database todolist;' -U postgres
    - psql -c 'create database car;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту youremail@smtp.ru (Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - pyotr1989@gmail.com
    on_success: never # default: change
    on_failure: always # default: always